VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsKIM"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public id As String
Public OpisaniyePerekhoda As String
Public Slozhost As Integer
Public D1 As Double
Public d2 As Double
Public Shirina As Double
Public Dlina As Double
Public KolVoPoverkhnostey As Double
Public KolVoSecheniy As Double
Public DopuskRazmera As Boolean
Public DopuskFormy As Boolean
Public DopuskRaspolozheniya As Boolean
Public OtOsi As Boolean
Public TrigernyyRezhim As Boolean
Public RadialnoyeIzmereniye As Boolean
Public LieneynoyeIzmereniye As Boolean
Public Massa As Double
