VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITechnologicalShape"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get tPeskostruy() As Double: End Property

Public Property Get tZakalka() As Double: End Property

Public Property Get tOtpusk() As Double: End Property

Public Property Get tUpakovka() As Double: End Property

Public Property Get tZaus() As Double: End Property

Public Property Get tPravka() As Double: End Property

Public Property Get Massa() As Double: End Property

Public Property Get Dlina() As Double: End Property

Public Property Get PerimetrIliDiametr() As Double: End Property

Public Property Get Material() As EnumMaterialy: End Property

Public Property Get PloshchadPoperSech() As Double: End Property

Public Property Get PloshchadPolnaya() As Double: End Property

Public Property Get Tonkostennaya() As Boolean: End Property

